#!/usr/bin/env python3
"""Shared vocabulary tables: the Estonian->English TaDiRAH bridge and the
TaDiRAH goal groups. Copied verbatim from method-galaxy/2_extract.py so the two
pipelines stay independent; the mapping was checked term by term against the 147
activity labels actually present in the Marketplace.

Two Estonian terms have no TaDiRAH2 counterpart and are kept as-is rather than
dropped: `kauguse mootmine` (distance measures, in v1 and gone from v2) and
`eemaldamine` (removing).
"""
ET2EN = {
    "analüüsimine": "Analyzing",
    "andmekaeve": "Data Mining",
    "andmete graafiline kujutamine": "Plotting",
    "andmete kogumine": "Collecting",
    "andmete puhastamine": "Data Cleansing",
    "andmete vastendus": "Data Mapping",
    "andmete visualiseerimine": "Data Visualization",
    "annoteerimine": "Annotating",
    "arhiveerimine": "Archiving",
    "arutamine": "Discussing",
    "avaldamine": "Publishing",
    "avastamine": "Discovering",
    "diagrammide koostamine": "Diagramming",
    "disain": "Designing",
    "eeltöötlus": "Preprocessing",
    "ekstraheerimine": "Extracting",
    "geoviitamine": "Georeferencing",
    "graafika, programmeerimine": "Graphics Programming",
    "haldus": "Managing",
    "identifitseerimine": "Identifying",
    "infootsing": "Information Retrieval",
    "järjestuste joondamine": "Sequence Alignment",
    "kärpimine": "Cropping",
    "kataloogimine": "Cataloging",
    "kirjutamine": "Creating",
    "klasteranalüüs": "Cluster Analysis",
    "kogumine": "Collecting",
    "kollatsioonimine": "Collating",
    "kontekstualiseerimine": "Contextualizing",
    "kontseptualiseerimine": "Conceptualizing",
    "koostamine": "Compiling",
    "korraldamine": "Organizing",
    "kujutuvastus": "Pattern Recognition",
    "lemmatiseerimine": "Lemmatizing",
    "levitamine": "Disseminating",
    "link-avaandmed": "Linked Open Data",
    "loomine": "Creating",
    "loomuliku keele töötlemine": "Natural Language Processing",
    "mängustamine": "Gamification",
    "märgendamine": "Tagging",
    "märgituvastus": "Data Recognition",
    "masinõpe": "Machine Learning",
    "meelsusanalüüs": "Sentiment Analysis",
    "modelleerimine": "Modeling",
    "nimede kasutamise reeglid": "Naming Convention",
    "nimeüksuste tuvastamine": "Named Entity Recognition",
    "optiline märgituvastus": "Optical Character Recognition",
    "optiline noodituvastus": "Optical Music Recognition",
    "otsing": "Searching",
    "päringud": "Querying",
    "põhikomponentide analüüs": "Principal Component Analysis",
    "põhjendamine": "Explanation",
    "postitamine": "Posting",
    "programmeerimine": "Programming",
    "püsi-identifikaator": "Persistent Identifier",
    "rikastamine": "Enriching",
    "ruumiandmete analüüs": "Spatial Analysis",
    "säilitamine": "Preserving",
    "selgitamine": "Explanation",
    "seosanalüüs": "Relational Analysis",
    "sirvimine": "Browsing",
    "sisuanalüüs": "Content Analysis",
    "stiilianalüüs": "Stylistic Analysis",
    "teadmuse avastamine": "Knowledge Discovery",
    "teemade modelleerimine": "Topic Modeling",
    "teisendamine": "Transformation",
    "teisendus": "Transformation",
    "teksti kategoriseerimine": "Text Categorization",
    "teooria loomine": "Theorizing",
    "toimetamine": "Editing",
    "tõlgendamine": "Interpreting",
    "tõlkimine": "Translating",
    "transkodeerimine": "Transcoding",
    "uurimine": "Exploration",
    "vastendus": "Mapping",
    "veebikaapimine": "Web Scraping",
    "visuaalne analüüs": "Visual Analysis",
    "võrdlemine": "Comparing",
}

KNOWN_UNMAPPED = {
    "eemaldamine": "removing — no TaDiRAH2 equivalent",
    "kauguse mõõtmine": "distance measures — in TaDiRAH v1, dropped in v2",
    "süntaksianalüüs": "syntactic analysis — no TaDiRAH2 equivalent",
}

GROUPS = {
    "Capture": ["Capturing", "Collecting", "Gathering", "Recording", "Imaging",
                "Photographing", "Transcribing", "Scanning", "Data Recognition",
                "Optical Character Recognition", "Optical Music Recognition",
                "Speech Recognizing", "Audio Recording", "Video Capture",
                "Web Crawling", "Web Scraping", "Data Ingestion", "Upload",
                "Crowdsourcing", "Pattern Recognition", "Genre Recognition"],
    "Creation": ["Creating", "Designing", "Programming", "Graphics Programming",
                 "Web Development", "Wireframing", "Writing", "Translating",
                 "Debugging", "Editing", "Formatting", "Lettering", "Diagramming",
                 "Plotting", "Gamification"],
    "Enrichment": ["Enriching", "Annotating", "Tagging", "Visual Annotation",
                   "Audio Annotation", "Lemmatizing", "POS-Tagging",
                   "Tree-Tagging", "Cleaning", "Data Cleansing", "Preprocessing",
                   "Semantification", "Linked Open Data", "Encoding",
                   "Segmenting", "Correcting", "Improving", "Adding",
                   "Highlighting", "Named Entity Recognition"],
    "Analysis": ["Analyzing", "Content Analysis", "Network Analysis",
                 "Relational Analysis", "Structural Analysis", "Visual Analysis",
                 "Spatial Analysis", "Stylistic Analysis", "Discourse Analysis",
                 "Rhetorical Analysis", "Contrastive Analysis",
                 "Collocation Analysis", "Cluster Analysis", "Topic Modeling",
                 "Sentiment Analysis", "Machine Learning", "Data Mining",
                 "Information Mining", "Knowledge Discovery",
                 "Knowledge Extraction", "Text Categorization", "Extracting",
                 "Co-Occurrence", "Authorship Attribution",
                 "Principal Component Analysis", "Sequence Alignment",
                 "Natural Language Processing", "Modeling", "Comparing",
                 "Data Visualization", "Mapping", "Data Mapping",
                 "Georeferencing", "Identifying"],
    "Interpretation": ["Interpreting", "Contextualizing", "Conceptualizing",
                       "Theorizing", "Explanation", "Description", "Defining",
                       "Abstract Thinking", "Associating", "Associate"],
    "Storage": ["Storing", "Archiving", "Preserving", "Preservation Metadata",
                "Bit Stream Preservation", "Migration", "Replication",
                "Cataloging", "Organizing", "Managing", "Identifier",
                "Persistent Identifier", "Digital Object Identifier",
                "Uniform Resource Identifier", "Naming Convention",
                "Integrating", "Merging", "Aggregating", "Compiling",
                "Converting", "Transformation", "Transcoding", "Modifying",
                "Cropping", "Collating"],
    "Dissemination": ["Disseminating", "Sharing", "Publishing",
                      "Digital Publishing", "Academic Publishing",
                      "Collaborating", "Discussing", "Teaching", "Posting",
                      "Social Networking", "Instant Messaging",
                      "Text Messaging", "Tweet", "User Generated Content",
                      "Audio Conferencing", "Video Conference", "Video Editing"],
    "Discovery": ["Discovering", "Searching", "Browsing", "Exploration",
                  "Finding", "Querying", "Information Retrieval"],
}
